# Generated by Django 2.0 on 2019-03-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.IntegerField(blank=True, default=1900, null=True),
        ),
    ]
