# Generated by Django 2.0 on 2019-04-25 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cell_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
