# Generated by Django 2.0 on 2019-04-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190426_0732'),
    ]

    operations = [
        
    ]
