# Generated by Django 2.0 on 2019-04-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190426_1158'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='person',
            name='cell_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        
    ]
